import type * as vscode from 'vscode';

export const GLM_MODELS: vscode.LanguageModelChatInformation[] = [
  {
    id: 'glm-5.1',
    name: 'GLM-5.1',
    family: 'glm',
    version: '5.1',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 200000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-5',
    name: 'GLM-5',
    family: 'glm',
    version: '5',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 205000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-5-turbo',
    name: 'GLM-5-Turbo',
    family: 'glm',
    version: '5-turbo',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 200000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-5v-turbo',
    name: 'GLM-5V-Turbo',
    family: 'glm',
    version: '5v-turbo',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 200000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: true, toolCalling: true},
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7',
    family: 'glm',
    version: '4.7',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 205000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-4.7-flash',
    name: 'GLM-4.7 Flash',
    family: 'glm',
    version: '4.7-flash',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 200000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-4.7-flashx',
    name: 'GLM-4.7 FlashX',
    family: 'glm',
    version: '4.7-flashx',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 200000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-4.6',
    name: 'GLM-4.6',
    family: 'glm',
    version: '4.6',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 205000,
    maxOutputTokens: 131072,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-4.6v',
    name: 'GLM-4.6V',
    family: 'glm',
    version: '4.6v',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 128000,
    maxOutputTokens: 33000,
    capabilities: {imageInput: true, toolCalling: true},
  },
  {
    id: 'glm-4.5',
    name: 'GLM-4.5',
    family: 'glm',
    version: '4.5',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 131072,
    maxOutputTokens: 98304,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-4.5-flash',
    name: 'GLM-4.5 Flash',
    family: 'glm',
    version: '4.5-flash',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 131072,
    maxOutputTokens: 98304,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-4.5-air',
    name: 'GLM-4.5 Air',
    family: 'glm',
    version: '4.5-air',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 131072,
    maxOutputTokens: 98304,
    capabilities: {imageInput: false, toolCalling: true},
  },
  {
    id: 'glm-4.5v',
    name: 'GLM-4.5V',
    family: 'glm',
    version: '4.5v',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 64000,
    maxOutputTokens: 16000,
    capabilities: {imageInput: true, toolCalling: true},
  },
];
